{% set name = "ydata-profiling" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-profiling-{{ version }}.tar.gz
  sha256: ff8f8cb41f86485b4a6d7bff32ff5ada747b1644f2b20bc5dd05cc616d1aef2e

build:
  entry_points:
    - ydata_profiling = ydata_profiling.controller.console:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0
  skip: True   #  [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - scipy=1.9.3
    - pandas >1.1,<1.6,!=1.4.0
    - matplotlib-base >=3.2,<3.7
    - pydantic >=1.8.1,<1.11
    - pyyaml >=5.0.0,<6.1
    - jinja2 >=2.11.1,<3.2
    - visions ==0.7.5
    - numpy >=1.16.0,<1.24
    # Related to HTML report
    - htmlmin ==0.1.12
    # Correlations
    - phik >=0.11.1,<0.13
    # Examples
    - requests >=2.24.0,<2.29
    # Progress bar
    - tqdm >=4.48.2,<4.65
    - seaborn >=0.10.1,<0.13
    - multimethod >=1.4,<1.10
    # metrics
    - statsmodels >=0.13.2,<0.14
    - typeguard >=2.13.2,<2.14
    - imagehash
    - pillow
    - ipywidgets >=7.5.1
  run_constrained:
    - jupyter-client >=5.3.4
    - jupyter-core >=4.6.3
    - tangled-up-in-unicode 0.2.0

test:
  imports:
    - pandas_profiling
    - ydata_profiling
  commands:
    - pip check
    - ydata_profiling --help
    - pandas_profiling --help
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-profiling
  summary: Generate profile report for pandas DataFrame
  description: |
    ydata-profiling primary goal is to provide a one-line Exploratory
    Data Analysis (EDA) experience in a consistent and fast solution.
    Like pandas df.describe() function, that is so handy, ydata-profiling
    delivers an extended analysis of a DataFrame while allowing the data
    analysis to be exported in different formats such as html and json.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://ydata-profiling.ydata.ai

extra:
  recipe-maintainers:
    - rxm7706