{% set name = "ydata-profiling" %}
{% set version = "4.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-profiling-{{ version }}.tar.gz
  sha256: 4aa0d6412a140194396e34f5ffd348223f0319d877b0243e765f30ae633ed51e

build:
  number: 0
  entry_points:
    - ydata_profiling = ydata_profiling.controller.console:main
    - pandas_profiling = ydata_profiling.controller.console:main
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37 or py>312]

requirements:
  host:
    - python
    - pip
    - setuptools >=72.0.0,<80.0.0
    - setuptools-scm >=8.0.0,<9.0.0
    - wheel >=0.38.4,<1.0.0
  run:
    - python
    - scipy >=1.4.1,<1.16
    - pandas >1.1,<3,!=1.4.0
    - matplotlib-base >=3.5,<3.10
    - pydantic >=2
    - pyyaml >=5.0.0,<6.1
    - jinja2 >=2.11.1,<3.2
    - visions >=0.7.5,<0.8.2
    - imagehash
    - pillow
    - numpy >=1.16.0,<2.2
    # Related to HTML report
    - htmlmin 0.1.12
    # Correlations
    - phik >=0.11.1,<0.13
    # Examples
    - requests >=2.24.0,<3
    # Progress bar
    - tqdm >=4.48.2,<5
    - seaborn >=0.10.1,<0.14
    - multimethod >=1.4,<2
    # metrics
    - statsmodels >=0.13.2,<1
    # type checking
    - typeguard >=3,<5
    - imagehash 4.3.1
    - wordcloud >=1.9.3
    - dacite >=1.8
    - numba >=0.56.0,<=0.61
  run_constrained:
    - jupyter >=1.0.0
    - ipywidgets >=7.5.1
    - tangled-up-in-unicode 0.2.0

test:
  imports:
    - pandas_profiling
    - ydata_profiling
  commands:
    - pip check
    - ydata_profiling --help
    - pandas_profiling --help
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-profiling
  summary: Generate profile report for pandas DataFrame
  description: |
    ydata-profiling primary goal is to provide a one-line Exploratory
    Data Analysis (EDA) experience in a consistent and fast solution.
    Like pandas df.describe() function, that is so handy, ydata-profiling
    delivers an extended analysis of a DataFrame while allowing the data
    analysis to be exported in different formats such as html and json.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://ydata-profiling.ydata.ai
  dev_url: https://github.com/ydataai/ydata-profiling

extra:
  recipe-maintainers:
    - rxm7706