{% set name = "ydata-profiling" %}
{% set version = "4.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-profiling-{{ version }}.tar.gz
  sha256: d9467ecc8474344347ad89a6839db14762f0230e53df94f83a04810b2fa6cbd7

build:
  entry_points:
    - ydata_profiling = ydata_profiling.controller.console:main
    - pandas_profiling = ydata_profiling.controller.console:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: True   #  [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - scipy  >=1.4.1,<1.14
    - pandas >1.1,<3,!=1.4.0
    - matplotlib-base >=3.2,<3.9
    - pydantic >=2
    - pyyaml >=5.0.0,<6.1
    - jinja2 >=2.11.1,<3.2
    - visions >=0.7.6
    - numpy >=1.16.0,<2
    # Related to HTML report
    - htmlmin 0.1.12
    # Correlations
    - phik >=0.11.1,<0.13
    # Examples
    - requests >=2.24.0,<3
    # Progress bar
    - tqdm >=4.48.2,<5
    - seaborn >=0.10.1,<0.14
    - multimethod >=1.4,<2
    # metrics
    - statsmodels >=0.13.2,<1
    # type checking
    - typeguard >=3,<5
    - imagehash 4.3.1
    - wordcloud >=1.9.1
    - dacite >=1.8
    - numba >=0.56.0,<1
  run_constrained:
    - jupyter-client >=5.3.4
    - jupyter-core >=4.6.3
    - ipywidgets >=7.5.1
    - tangled-up-in-unicode 0.2.0

test:
  imports:
    - pandas_profiling
    - ydata_profiling
  commands:
    - pip check
    - ydata_profiling --help
    - pandas_profiling --help
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-profiling
  summary: Generate profile report for pandas DataFrame
  description: |
    ydata-profiling primary goal is to provide a one-line Exploratory
    Data Analysis (EDA) experience in a consistent and fast solution.
    Like pandas df.describe() function, that is so handy, ydata-profiling
    delivers an extended analysis of a DataFrame while allowing the data
    analysis to be exported in different formats such as html and json.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://ydata-profiling.ydata.ai
  dev_url: https://github.com/ydataai/ydata-profiling

extra:
  recipe-maintainers:
    - rxm7706